# Generated by Django 5.0.7 on 2024-07-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Watcher", "Watcher"),
                            ("North", "North"),
                            ("Nightmare", "Nightmare"),
                            ("Curse", "Curse"),
                            ("Infernal", "Infernal"),
                            ("Piercer", "Piercer"),
                            ("Esoteric", "Esoteric"),
                            ("Chaos Dominion", "Chaos_Dominion"),
                            ("Unnamable", "Unnamable"),
                        ],
                        default="Watcher",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeroClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Rarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Rare", "Rare"),
                            ("Epic", "Epic"),
                            ("Legendary", "Legendary"),
                        ],
                        default="Rare",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wor.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("health", models.IntegerField(default=0)),
                ("attack", models.IntegerField(default=0)),
                ("defense", models.IntegerField(default=0)),
                ("magic_resistance", models.IntegerField(default=0)),
                ("Cost", models.IntegerField(default=0)),
                ("block", models.IntegerField(default=0)),
                ("revival_time", models.IntegerField(default=0)),
                ("attack_interval", models.IntegerField(default=0)),
                ("rage_regen_auto", models.IntegerField(default=0)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wor.faction"
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wor.heroclass"
                    ),
                ),
                (
                    "rarity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wor.rarity"
                    ),
                ),
            ],
        ),
    ]
