# Generated by Django 5.0.7 on 2024-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroclass",
            name="name",
            field=models.CharField(
                choices=[
                    ("Fighter", "Fighter"),
                    ("Mage", "Mage"),
                    ("Marksman", "Marksman"),
                    ("Healer", "Healer"),
                    ("Defender", "Defender"),
                ],
                default="Fighter",
                max_length=10,
            ),
        ),
    ]
