# Generated by Django 5.0.7 on 2024-07-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wor", "0002_heroclass_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="classe",
            new_name="heroclass",
        ),
        migrations.AlterField(
            model_name="character",
            name="attack_interval",
            field=models.FloatField(default=2.6),
        ),
        migrations.AlterField(
            model_name="character",
            name="revival_time",
            field=models.IntegerField(default=60),
        ),
    ]
