# Generated by Django 5.0.7 on 2024-08-02 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0002_amulet_user_chestplate_user_ring_user_weapon_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='amulet',
            name='user',
            field=models.ForeignKey(
                default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chestplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ring',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wristband',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pantheon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk_bonus', models.IntegerField(default=0)),
                ('hp_bonus', models.IntegerField(default=0)),
                ('rage_regen', models.IntegerField(default=0)),
                ('crit_dmg', models.IntegerField(default=0)),
                ('healing_effect', models.IntegerField(default=0)),
                ('atk_spd', models.IntegerField(default=0)),
                ('def_bonus', models.IntegerField(default=0)),
                ('mRes_bonus', models.IntegerField(default=0)),
                ('crit_rate', models.IntegerField(default=0)),
                ('ragen_regen_auto', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
