# Generated by Django 5.0.7 on 2024-08-03 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0003_alter_amulet_user_alter_chestplate_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantheon',
            name='atk_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='atk_spd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='crit_dmg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='crit_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='def_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='healing_effect',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='hp_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='mRes_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='rage_regen',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pantheon',
            name='ragen_regen_auto',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
