# Generated by Django 5.0.7 on 2024-07-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wor", "0003_rename_classe_character_heroclass_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="Cost",
            new_name="cost",
        ),
        migrations.RenameField(
            model_name="faction",
            old_name="name",
            new_name="faction",
        ),
        migrations.RenameField(
            model_name="heroclass",
            old_name="name",
            new_name="heroclass",
        ),
        migrations.RenameField(
            model_name="rarity",
            old_name="name",
            new_name="rarity",
        ),
        migrations.RemoveField(
            model_name="character",
            name="faction",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
