# Generated by Django 5.0.7 on 2024-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wor", "0004_primaryattributes_secondaryattributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="faction",
            field=models.ManyToManyField(to="wor.faction"),
        ),
    ]
