# Generated by Django 5.0.7 on 2024-08-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0004_alter_pantheon_atk_bonus_alter_pantheon_atk_spd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='artifact',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.artifact'
            ),
        ),
    ]
