# Generated by Django 5.0.7 on 2024-08-04 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0005_character_artifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='artifact',
        ),
        migrations.AddField(
            model_name='artifact',
            name='character',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.character'
            ),
        ),
    ]
