# Generated by Django 5.0.7 on 2024-08-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0006_remove_character_artifact_artifact_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='amulet',
        ),
        migrations.RemoveField(
            model_name='character',
            name='chestplate',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ring',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wristband',
        ),
        migrations.AddField(
            model_name='amulet',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wor.character'),
        ),
        migrations.AddField(
            model_name='character',
            name='charToAmulet',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='amulet',
                to='wor.amulet',
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='charToChestplate',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chestplate',
                to='wor.chestplate',
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='charToRing',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ring', to='wor.ring'
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='charToWeapon',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='weapon',
                to='wor.weapon',
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='charToWristband',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='wristband',
                to='wor.wristband',
            ),
        ),
        migrations.AddField(
            model_name='chestplate',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wor.character'),
        ),
        migrations.AddField(
            model_name='ring',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wor.character'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wor.character'),
        ),
        migrations.AddField(
            model_name='wristband',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wor.character'),
        ),
    ]
