# Generated by Django 5.0.7 on 2024-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wor", "0006_amulet_chestplate_ring_weapon_wristband_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chestplate",
            name="set_name",
            field=models.CharField(
                choices=[
                    ("light's grace", "Light's Grace"),
                    ("wicked vengeance", "Wicker Vengeance"),
                    ("immortal warrior", "Immortal Warrior"),
                    ("warlord", "warlord"),
                    ("salvation", "Salvation"),
                    ("life force", "Life Force"),
                    ("calamity", "Calamity"),
                    ("whirlwind", "Whirlwind"),
                    ("annihilating might", "Annihilating Might"),
                    ("lifegiver", "Lifegiver"),
                    ("iron fortress", "Iron Fortress"),
                    ("wrathful onslaught", "Wrathful Onslaught"),
                    ("savage strike", "Savage Strike"),
                    ("deadly aim", "Deadly Aim"),
                    ("vitality", "Vitality"),
                    ("juggernaut", "Juggernaut"),
                ],
                default="calamity",
                max_length=18,
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="set_name",
            field=models.CharField(
                choices=[
                    ("light's grace", "Light's Grace"),
                    ("wicked vengeance", "Wicker Vengeance"),
                    ("immortal warrior", "Immortal Warrior"),
                    ("warlord", "warlord"),
                    ("salvation", "Salvation"),
                    ("life force", "Life Force"),
                    ("calamity", "Calamity"),
                    ("whirlwind", "Whirlwind"),
                    ("annihilating might", "Annihilating Might"),
                    ("lifegiver", "Lifegiver"),
                    ("iron fortress", "Iron Fortress"),
                    ("wrathful onslaught", "Wrathful Onslaught"),
                    ("savage strike", "Savage Strike"),
                    ("deadly aim", "Deadly Aim"),
                    ("vitality", "Vitality"),
                    ("juggernaut", "Juggernaut"),
                ],
                default="calamity",
                max_length=18,
            ),
        ),
    ]
