# Generated by Django 5.0.7 on 2024-08-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0007_remove_character_amulet_remove_character_chestplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amulet',
            name='character',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charToAmulet',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charToChestplate',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charToRing',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charToWeapon',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charToWristband',
        ),
        migrations.RemoveField(
            model_name='chestplate',
            name='character',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='character',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='character',
        ),
        migrations.RemoveField(
            model_name='wristband',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='amulet',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.amulet'
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='chestplate',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.chestplate'
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='ring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.ring'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.weapon'
            ),
        ),
        migrations.AddField(
            model_name='character',
            name='wristband',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.wristband'
            ),
        ),
    ]
