# Generated by Django 5.0.7 on 2024-07-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wor", "0008_amulet_set_name_ring_set_name_wristband_set_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="magic_resistance",
            new_name="mRes",
        ),
    ]
