# Generated by Django 5.0.7 on 2024-08-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0008_remove_amulet_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='equiped_character',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='weaponToChar',
                to='wor.character',
            ),
        ),
    ]
