# Generated by Django 5.0.7 on 2024-07-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wor", "0009_rename_magic_resistance_character_mres"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="crit_dmg",
            field=models.IntegerField(default=150),
        ),
    ]
