# Generated by Django 5.0.7 on 2024-08-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0009_weapon_equiped_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='amulet',
            name='equiped_character',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amulet_id', to='wor.character'
            ),
        ),
        migrations.AddField(
            model_name='chestplate',
            name='equiped_character',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chestplate_id', to='wor.character'
            ),
        ),
        migrations.AddField(
            model_name='ring',
            name='equiped_character',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ring_id', to='wor.character'
            ),
        ),
        migrations.AddField(
            model_name='wristband',
            name='equiped_character',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wristband_id', to='wor.character'
            ),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='equiped_character',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_id', to='wor.character'
            ),
        ),
    ]
