# Generated by Django 5.0.7 on 2024-08-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0010_amulet_equiped_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amulet',
            name='equiped_character',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amulet_id', to='wor.character'
            ),
        ),
        migrations.AlterField(
            model_name='character',
            name='amulet',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.amulet'
            ),
        ),
        migrations.AlterField(
            model_name='character',
            name='chestplate',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.chestplate'
            ),
        ),
        migrations.AlterField(
            model_name='character',
            name='ring',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.ring'
            ),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapon',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.weapon'
            ),
        ),
        migrations.AlterField(
            model_name='character',
            name='wristband',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.wristband'
            ),
        ),
        migrations.AlterField(
            model_name='chestplate',
            name='equiped_character',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chestplate_id', to='wor.character'
            ),
        ),
        migrations.AlterField(
            model_name='ring',
            name='equiped_character',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ring_id', to='wor.character'
            ),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='equiped_character',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon_id', to='wor.character'
            ),
        ),
        migrations.AlterField(
            model_name='wristband',
            name='equiped_character',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wristband_id', to='wor.character'
            ),
        ),
    ]
