# Generated by Django 5.0.7 on 2024-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0010_character_crit_dmg'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attack_speed',
            field=models.IntegerField(default=100),
        ),
    ]
