# Generated by Django 5.0.7 on 2024-08-04 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0011_alter_amulet_equiped_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chestplate',
            name='equiped_character',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='equiped_character',
        ),
        migrations.AddField(
            model_name='weapon',
            name='eqp_character',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_id', to='wor.character'
            ),
        ),
    ]
