# Generated by Django 5.0.7 on 2024-08-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0012_remove_chestplate_equiped_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amulet',
            name='equiped_character',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='equiped_character',
        ),
        migrations.RemoveField(
            model_name='wristband',
            name='equiped_character',
        ),
    ]
