# Generated by Django 5.0.7 on 2024-08-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0013_remove_amulet_equiped_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='weapon',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='eqp_character',
        ),
        migrations.AddField(
            model_name='weapon',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.character'),
        ),
    ]
