# Generated by Django 5.0.7 on 2024-08-04 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0014_remove_character_weapon_remove_weapon_eqp_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='amulet',
        ),
        migrations.RemoveField(
            model_name='character',
            name='chestplate',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ring',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wristband',
        ),
        migrations.AddField(
            model_name='amulet',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.character'),
        ),
        migrations.AddField(
            model_name='chestplate',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.character'),
        ),
        migrations.AddField(
            model_name='ring',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.character'),
        ),
        migrations.AddField(
            model_name='wristband',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.character'),
        ),
    ]
