# Generated by Django 5.0.7 on 2024-08-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0015_remove_character_amulet_remove_character_chestplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='character',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.character'
            ),
        ),
    ]
