# Generated by Django 5.0.7 on 2024-08-04 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0016_alter_artifact_character'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0)),
                ('ragen_regen_atked', models.IntegerField(default=0)),
                ('atk', models.IntegerField(default=0)),
                ('revival_time', models.IntegerField(default=0)),
                ('ragen_regen_basic_atk', models.IntegerField(default=0)),
                ('crit_rate', models.IntegerField(default=0)),
                ('crit_dmg', models.IntegerField(default=0)),
                ('init_rage', models.IntegerField(default=0)),
                (
                    'faction',
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wor.faction'
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
