# Generated by Django 5.0.7 on 2024-08-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0017_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='hp',
        ),
        migrations.AddField(
            model_name='collection',
            name='hp200',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='hp50',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='ragen_regen_atked',
            field=models.BooleanField(default=False),
        ),
    ]
