# Generated by Django 5.0.7 on 2024-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0018_remove_collection_hp_collection_hp200_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='ragen_regen_atked',
            new_name='rage_regen_atked',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='atk',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='crit_dmg',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='crit_rate',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='init_rage',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='ragen_regen_basic_atk',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='revival_time',
        ),
        migrations.AddField(
            model_name='collection',
            name='atk50',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='crit_dmg_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='crit_rate_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='hp400',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='init_rage_30',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='rage_regen_basic_atk_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='revival_time_minus_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction',
            field=models.CharField(
                choices=[
                    ('Watcher', 'Watcher'),
                    ('North', 'North'),
                    ('Nightmare', 'Nightmare'),
                    ('Curse', 'Curse'),
                    ('Infernal', 'Infernal'),
                    ('Piercer', 'Piercer'),
                    ('Esoteric', 'Esoteric'),
                    ('Chaos Dominion', 'Chaos_Dominion'),
                    ('Arbiters', 'Arbiters'),
                    ('Unnamable', 'Unnamable'),
                ],
                default='Watcher',
                max_length=15,
            ),
        ),
    ]
