# Generated by Django 5.0.7 on 2024-08-05 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0019_rename_ragen_regen_atked_collection_rage_regen_atked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='faction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wor.faction'),
        ),
    ]
