# Generated by Django 5.0.7 on 2024-08-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wor', '0021_remove_collection_atk50_remove_collection_hp200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='rage_regen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='rage_regen_atked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='rage_regen_basic_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction',
            field=models.CharField(
                choices=[
                    ('Watcher', 'Watcher'),
                    ('North', 'North'),
                    ('Nightmare', 'Nightmare'),
                    ('Curse', 'Curse'),
                    ('Infernal', 'Infernal'),
                    ('Piercer', 'Piercer'),
                    ('Esoteric', 'Esoteric'),
                    ('Chaos Dominion', 'Chaos Dominion'),
                    ('Arbiters', 'Arbiters'),
                    ('Unnamable', 'Unnamable'),
                ],
                default='Watcher',
                max_length=15,
            ),
        ),
    ]
